spring:
  application:
    name: LibraryDirections

server:
  port: 8083

library:
  directions:
    destination-address: "Ομήρου 9, Ταύρος, Αθήνα, Ελλάδα"
    maps-base-url: "https://maps.googleapis.com/maps/api/directions/json"
    api-key: "YOUR_GOOGLE_MAPS_API_KEY"